project: 'flow-bc'
program: train.py
method: grid
name: "Walker2d-gaussian-bc"

parameters:
  policy:
    value: gaussian
  num-epochs:
    value: 100
  batch-size:
    value: 256
  depth:
    value: 2
  hidden-dim:
    value: 256
  eval-interval:
    value: 10
  eval-episodes:
    value: 10
  env-name:
    value: mujoco/walker2d/medium-v0
  save-path:
    value: 'weights/walker2d/gaussian_baseline.pt'
  lr:
    value: 0.0002
  seed:
    values: [1, 2, 3]